// @ts-nocheck
// "How to use this page" guides for every screen: [intro, steps (HTML), tip].
export const HELP: Record<string, any> = {
 dashboard:['Your starting point: key numbers and the items waiting for you, based on your role.',['Read the tiles for the headline numbers.','Work through <b>Needs attention</b> from top to bottom; select a row to jump to that screen.','Use the menu on the left for everything else. You only see modules your role allows.'],'Approvals waiting for you always appear at the top of Needs attention.'],
 leads:['Every enquiry, from website, expos, dealers or the installed base, on one board.',['Choose <b>New lead</b> and pick an existing customer or type a new one.','Move a card by changing its stage: New, Qualified, Quoted, Won or Lost.','On a New or Qualified lead, choose <b>Create quote</b> to start a quotation with the customer and product filled in.','Watch the follow-up tags: red means overdue.'],'Leads created from AMC alerts carry the machine serial number.'],
 customers:['Customer master with location, GST details, installed machines and receivables.',['Choose <b>Add customer</b> or <b>Edit</b> on a row.','For Indian customers, pick the state and enter the 15-character GSTIN; its first two digits must match the state code.','Leave the state blank and enter a country for export customers.'],'A tax invoice cannot be raised for an Indian customer without a valid GSTIN.'],
 quotes:['Quotations from the price list, with approval before they go to the customer.',['Choose <b>New quotation</b>, pick the customer, up to three items and a discount.','Add a note to the approver; it is required above the 5% discount limit.','Choose <b>Submit for approval</b>. Admin approves, rejects or asks for more details.','Once approved, <b>Mark sent</b>, then <b>Convert to sales order</b> when the customer\'s PO arrives.'],'Filter by status with the buttons above the table.'],
 orders:['Sales orders created from the customer\'s PO, with progress from advance to installation.',['Select an order to open it and see the progress strip.','<b>Record advance received</b> with the UTR; production is released only after an advance.','<b>Release production</b> creates one work order per line.','When items are ready, <b>Dispatch ready items</b> ships them and raises the GST invoice.'],'An order can be dispatched in parts; the status shows Partly dispatched.'],
 invoices:['GST tax invoices raised at dispatch, and customer payments against them.',['Select an invoice to view the full tax invoice: HSN, CGST/SGST or IGST, amount in words.','Choose <b>Payment</b> to record money received, in full or in part, with the UTR.','Watch the Overdue tile: terms are 30 days from the invoice date.'],'The customer\'s advance is adjusted automatically against the first invoices of the order.'],
 products:['Finished goods: machines and change parts, with specifications and BOM status.',['Choose <b>Add product</b> to create a new finished good; you then go straight to its BOM.','Use <b>Edit</b> to change name, family, HSN, price or specifications (one "Label: value" per line).','Choose <b>View BOM</b> or <b>Create BOM</b> on a card.'],'A product without a BOM shows "No BOM" in amber.'],
 bom:['Bill of materials: raw materials per one unit, grouped by sub-assembly, with cost analysis.',['Pick the product at the top.','Choose <b>Edit BOM</b> (or <b>Create BOM</b>), add lines, or copy from a similar product.','Write what changed and save; each save is a new version.','Read the cost by category and the top cost drivers after saving.'],'The full step-by-step guide is under Help › How to create a BOM.'],
 materials:['Raw material master with stock, reorder levels and where each is used.',['Search by code or description, or filter by category.','Choose <b>Add material</b> or <b>Edit</b> to maintain code, category, unit and rate.','Amber and red tags show items below reorder level or out of stock.'],'Stock changes only through GRN, material issue and receipts, never by editing.'],
 mrp:['Material planning: what open orders need, against stock and what is already on order.',['Tick the sales orders to plan for.','Choose <b>Run material planning</b>.','Review shortages in red; On order counts open indents and POs.','Choose <b>Raise indent for shortages</b> to send them for approval.'],'Orders whose material is already issued are skipped automatically.'],
 workorders:['Production jobs, one per sales order line, moved stage by stage.',['<b>Release</b> work orders for orders that have an advance.','Choose <b>Complete</b> on a row to finish the current stage.','At Material issue, stock is deducted from the BOM, or taken from a fully issued requisition.','A job at Ready can be dispatched.'],'Machines and change parts follow different stage lists.'],
 dispatch:['Ship ready items with a delivery challan and GST invoice.',['Choose <b>Prepare dispatch</b> on an order.','Tick the items to ship now and the quantity; untick items that should wait.','Enter vehicle and transporter, and the e-way bill (domestic, above ₹50,000) or shipping bill (export).','Tick every document, then <b>Dispatch and create GST invoice</b>.'],'Machines appear in the installed base as Installation pending.'],
 purchase:['One view of purchasing, from indent to vendor payment.',['Select a tile to open the list behind it.','Check <b>Open purchase order lines</b> for what is still due and what is overdue.','Use <b>Vendor performance</b> to compare on-time delivery and QC acceptance.'],'Rejected quantity stays in the PO balance until the vendor replaces it or the PO is short-closed.'],
 vendors:['Vendor master with GST details, payment terms and performance.',['Choose <b>Add vendor</b> or <b>Edit</b>.','Enter the state and GSTIN; this decides CGST+SGST or IGST on POs and bills.','Set payment terms in days; bill due dates follow them.'],'On-time and QC-accepted percentages are calculated from gate entries and GRNs.'],
 indent:['Indents: departments ask for material to be bought.',['Choose <b>New indent</b>, give a reason and need-by date, and add lines.','The approver can approve all, lower quantities to approve part, or reject with a remark.','Approved quantity moves to a purchase order.'],'Material planning raises indents for shortages in one click.'],
 po:['Purchase orders to vendors, approved before they go out and received in parts.',['Create a PO from an approved indent, or a <b>New direct PO</b> for urgent needs (reason required).','The approver approves or rejects.','Open a PO to see line status, <b>View PO document</b> with GST, <b>Record gate entry</b> when material arrives, or <b>Short-close</b> a balance the vendor cannot supply.'],'Line status shows Pending, Part received, Received, Overdue or Short closed.'],
 gate:['Gate pass: inward entries against POs, and outward passes for returns and job work.',['<b>Inward</b>: choose the PO, enter vehicle and DC/invoice, what arrived, and anything rejected at the gate with a reason.','Stores then creates the GRN for the material passed at the gate.','<b>Outward</b>: raise a pass for rejected material or job work; returnable passes are received back in parts.'],'Material rejected at the gate never enters stock and stays open on the PO.'],
 grn:['Goods receipt: count what came in, then QC decides.',['Stores chooses <b>Create GRN</b> from an inward entry and enters the counted quantity.','QC opens the GRN, enters the accepted quantity per line and a reason for anything rejected, then approves.','Only accepted quantity goes into stock and counts against the PO.','For rejections, choose <b>Create return gate pass</b>.'],'Accepted material then goes to Vendor bills for billing.'],
 bills:['Vendor bills matched against PO and GRN before payment.',['Choose <b>Book vendor bill</b> and pick the GRN.','Enter the vendor\'s invoice number and the quantity and rate as billed.','A matched bill goes straight to payment. A mismatch (quantity above accepted, or rate above PO) is held for approval.','The approver pays the matched value; the difference becomes a debit note.','<b>Record vendor payment</b> in full or in part.'],'Debit notes are listed on their own tab.'],
 mr:['Material requisition: production asks stores for material.',['Choose <b>New requisition</b>; pick a work order and <b>Fill from BOM</b>, or add lines.','The approver approves all, part or rejects.','Stores <b>Responds</b>: issues what is in stock, raises a purchase indent for any shortfall, or sends it back for clarification (production answers with <b>Answer stores</b>).','Production <b>Confirms receipt</b>, rejecting anything wrong or damaged back to stores.'],'When a work order\'s requisition is fully issued, its material-issue stage does not deduct stock again.'],
 service:['Installed base, installation, warranty, AMC and service tickets.',['For delivered machines, choose <b>Record installation</b> after IQ/OQ; the warranty starts then.','Use <b>Create renewal lead</b> on machines with AMC due or expired.','Raise a <b>New service ticket</b> and close it when resolved.'],'Machines are sorted with the most urgent first.'],
 staff:['People who can sign in, with their role and login.',['Choose <b>Add staff</b>; fill basic details, role, user ID and password.','Use <b>Password</b> to reset a password; passwords are never shown.','Deactivate people who leave; they can no longer sign in.'],'At least one active person must keep full access to Staff and Role master.'],
 lists:['The choices offered in drop-downs (units, lead sources, departments, states, BOM groups, ...) and the company details printed on invoices and POs.',['Pick a group: Materials, Sales & CRM, Company or Engineering.','Choose <b>Add</b> to add an entry, or <b>Edit</b> to change one.','New entries appear in the drop-downs straight away, for everyone.'],'Each list is a table in the database. Who can change it depends on the role: for example, units need full access to Raw materials, departments need full access to the Staff master.'],
 roles:['Roles decide which modules a person sees and which documents they approve.',['Choose <b>Add role</b> or <b>Edit</b>.','Set each module to No access, View only or Full access.','Tick the documents this role can approve.'],'Administrator is a system role and cannot be changed.'],
 stores:['The store in-charge\'s desk: everything waiting for stores, in order of urgency.',['Work down <b>Waiting for stores</b>; each row has the button for the next step.','<b>Respond</b> to shop-floor requisitions: issue what is in stock, indent the shortfall, or send back for clarification.','<b>Create GRN</b> for material waiting at the gate, and return rejected material.','Check indents from the shop floor: the row shows how many lines are already in stock.','Use the tiles to open Inventory, Procurement planning or GRN.'],'Rows marked Now mean stock has arrived for a request that was waiting.'],
 inventory:['Stock by item and bin, what is reserved for approved requisitions and what is free to issue.',['Search by item, code or bin, or filter to Below reorder or Reserved.','Select an item to open its <b>stock card</b>: every receipt, issue, return and adjustment with the running balance.','After a physical count, raise a <b>Stock adjustment</b>; it posts only after approval.','Use the Stock ledger tab to see all movements.'],'Available = on hand − reserved. Reserved is approved requisition quantity not yet issued.'],
 planning:['Replenishment plan from reorder levels and open-order demand.',['Read Projected: on hand + on order − reserved − order demand.','Lines below the reorder level get a suggestion that tops them up to the maximum.','Tick the lines to buy and choose <b>Raise indent for selected</b>; review and submit.','Switch to All items to see what is covered.'],'Order demand comes from the BOMs of open sales orders whose material is not yet issued.'],
 help:['Step-by-step guides for the main processes.',['Pick a guide on the left.','Use the buttons in each guide to jump to the screen it describes.'],'Every screen also has its own How to use this page button.']
};
HELP.materials[1].push('Under <b>Alternate units</b>, list how the item is bought or counted, for example "sheet 1250×2500 = 49.56" for a kg item. Use the <b>metal weight calculator</b> to work out kg per sheet, block, length or metre.');
HELP.po[1].push('When ordering, choose the <b>order unit</b> (sheets, blocks, lengths or kg); quantity and rate convert to the stock unit automatically.');
HELP.gate[1].push('Record arrivals in the unit on the delivery challan; it is converted to the stock unit.');
HELP.grn[1].push('For metal, count the pieces and enter the <b>weighed kg</b>: stock is taken at the actual weight, and a variance above ±3% of the theoretical weight is flagged.');
HELP.bills[1].push('If the vendor bills in kg for a PO placed in pieces (or the reverse), choose the <b>billed unit</b>; the match converts both to the stock unit.');
HELP.combos=['Parent–child item sets. Each main item (machine or change part) carries the child items that go with it on a quotation.',[
 'Pick a main item on the left to see its <b>standard scope</b> and <b>optional add-ons</b>.',
 'Choose <b>Edit combo set</b> (or <b>Create combo set</b>). For each line pick the child item, set it to <b>Standard</b> or <b>Optional</b>, choose whether its price is <b>included</b> in the main item or <b>charged at list</b>, and set the quantity per main item.',
 'Use <b>Copy lines from</b> to start from a similar machine, for example EB-160 for EB-140.',
 'Give a reason and choose <b>Save combo set</b>. Each save becomes a new revision with history.',
 'Spares, accessories, services and documents live in the <b>Child item master</b> tab; add new ones with <b>Add child item</b>.'],
 'Change parts and machines used as child items get their own work orders; spares, accessories, services and documents ship with their main item.'];
HELP.quotes[1].splice(0,1,'Choose <b>New quotation</b> and pick the customer. Pick up to four <b>main items</b>: each one\'s combo set drops down below it with the standard scope ticked.','Tick the optional add-ons the customer wants and adjust quantities. Unticking a standard item needs a note to Admin.');
HELP.quotes[2]='Included child items show as "Included" and carry no extra value. Filter by status with the buttons above the table.';
if(HELP.orders) HELP.orders[1].push('Child items from a combo set show under their main item. They need no work order and are ready to ship when the main item is ready.');
HELP.crm=['One place for every customer conversation: follow-ups, calls, visits, e-mails, demos and collection calls, linked to leads, quotes, orders and invoices.',[
 'Start with <b>Follow-ups</b>: overdue items are red. Choose <b>Complete</b>, note what was discussed and the outcome, and set the <b>next follow-up</b> so nothing drops.',
 'Choose <b>Log activity</b> after any call, visit or demo. Link it to a lead, quote, order or invoice so it shows on that customer\'s history.',
 'Keep <b>Contacts</b> up to date with each person\'s role in buying: decision maker, purchase, engineering or accounts. Reminders go to the accounts contact.',
 '<b>Pipeline</b> shows the funnel from new leads to orders, and quotes sitting with customers that need chasing.',
 'Select any customer name to open the <b>customer overview</b>: contacts, activities, open sales, invoices and installed machines together.'],
 'Logging an activity on a lead with outcome Positive or Interested moves a New lead to Qualified and sets its next follow-up date.'];
HELP.receivables=['Customer dues by age, with the follow-up on every overdue invoice.',[
 '<b>Ageing by customer</b> splits each customer\'s balance into not due, 1–30, 31–60, 61–90 and over 90 days past due. Select a row for the customer overview.',
 'On <b>Open invoices</b>, choose <b>Follow up</b> to log a collection call. Record the promise to pay; a promise that passes unpaid is flagged as broken.',
 'Choose <b>Reminder</b> to draft a friendly, second or final reminder, set by the oldest overdue invoice. Copy it into your e-mail, then <b>Mark as sent</b> to log it.',
 'Record money received with <b>Payment</b>. <b>Receipts</b> lists advances and invoice payments; <b>Customer ledger</b> is the statement of account.',
 'Credit days and limits are set per customer from the customer overview; new invoices take their due date from the credit days.'],
 'Advances received against orders not yet invoiced are shown separately and adjusted automatically on the invoice at dispatch.'];
HELP.payables=['Vendor dues, due dates and the payment run.',[
 '<b>Due for payment</b> lists approved bills by due date. Due date = vendor bill date + vendor terms, capped at 45 days for MSME vendors.',
 'Tick bills (or <b>Select due in 7 days</b>), then <b>Pay selected</b>. Adjust any amount for a part payment, enter one bank batch or UTR reference and record the run.',
 '<b>Ageing by vendor</b> shows how old each vendor\'s balance is, with debit notes raised on mismatched bills.',
 '<b>Payments</b> is the payment history; <b>Vendor ledger</b> shows bills, debit notes and payments with the running balance.'],
 'Bills on hold for a 3-way mismatch are not payable until approved in Vendor bills.'];
HELP.forecast=['Projects the next 3 or 6 months from 12 months of sales, compares six methods, and converts the plan into materials to buy ahead.',[
 'Pick what to forecast: machines, change parts or all products by revenue, or any single product in units or revenue.',
 '<b>Auto</b> uses the method that was most accurate on the last 4 months. <b>Methods compared</b> shows each method\'s accuracy and bias; choose <b>Use</b> to switch.',
 'The shaded band is the 80% range. The blue dashed line appears when booked orders plus the weighted CRM pipeline are higher than the statistical forecast.',
 'In <b>Plan for the next 3 months</b>, override any quantity with what sales and production agree.',
 '<b>Raw material needed</b> shows what to buy beyond open orders for the unbooked plan; <b>Raise indent</b> sends it to purchase for approval.'],
 'Accuracy is 100% minus the weighted absolute percentage error (WAPE). Bias above zero means the method tends to over-forecast.'];

// Search tips (every guide except Help and the demand forecast, as in the prototype).
HELP.help[1].push('Use the search bar at the top of every screen, or press <b>Ctrl+K</b> to search every record.');
Object.keys(HELP).forEach(k=>{ if(k!=='help'&&k!=='forecast'&&Array.isArray(HELP[k][1])) HELP[k][1].push('<b>Search:</b> type in the bar under the title, or use a quick filter. Try column searches like <code>customer:kaveri</code> and numbers like <code>balance&gt;1L</code>; press <b>Tips</b> for more.'); });
