// Generates the MEK-SEL ERP table migration and the sample-data migration from src/erp/schema.ts.
//   npx tsx scripts/gen-db.ts
// Re-run it after changing schema.ts or the sample data in engine.ts, and commit both files.
import { writeFileSync } from "node:fs";
import {
  COUNTERS_TABLE,
  LISTS,
  TABLES,
  parentKey,
  type ChildSpec,
  type Col,
  type ColType,
  type ListSpec,
  type TableSpec,
} from "../src/erp/schema";
import { sampleRows } from "../src/erp/collections";

const TABLES_FILE = "supabase/migrations/20261001150000_meksel_erp_tables.sql";
const SAMPLE_FILE = "supabase/migrations/20261001150100_meksel_erp_sample_data.sql";

const SQLT: Record<ColType, string> = {
  t: "text",
  n: "numeric",
  i: "integer",
  b: "boolean",
  ts: "timestamptz",
  d: "date",
  ta: "text[]",
};
const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const lit = (v: any, type?: ColType | "j"): string => {
  if (v === null || v === undefined) return "NULL";
  if (type === "j") return q(JSON.stringify(v)) + "::jsonb";
  if (type === "ta") return v.length ? "ARRAY[" + v.map(q).join(",") + "]" : "'{}'::text[]";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return q(String(v));
};

type Phys = {
  name: string;
  coll: string;
  doc: string;
  cols: [string, ColType | "j" | "int", string][];
  pk: string[];
  parent?: { table: string; col: string; ref: string };
  listCols?: Col[];
};
const ALL: Phys[] = [];
const header = (t: TableSpec): Phys => ({
  name: t.table,
  coll: t.coll,
  doc: t.doc,
  pk: [t.pk.column],
  cols: [
    [t.pk.column, t.pk.type, "NOT NULL"],
    ...t.cols.map((c): [string, ColType, string] => [c.column, c.type, ""]),
    ...(t.ordered ? [["sort_order", "int", ""] as any] : []),
  ],
});
const child = (t: TableSpec, c: ChildSpec): Phys => ({
  name: c.table,
  coll: t.coll,
  doc: c.doc,
  pk: c.kind === "map" ? [parentKey(t), c.keyCol!.column] : [parentKey(t), "line_no"],
  cols: [
    [parentKey(t), t.pk.type, "NOT NULL"],
    ...(c.keyCol ? [[c.keyCol.column, c.keyCol.type, "NOT NULL"] as any] : []),
    ["line_no", "int", "NOT NULL"],
    ...c.cols.map((x): [string, ColType, string] => [x.column, x.type, ""]),
  ],
  parent: t.headerless ? undefined : { table: t.table, col: parentKey(t), ref: t.pk.column },
});
const list = (l: ListSpec): Phys => ({
  name: l.table,
  coll: l.coll,
  doc: l.doc,
  pk: ["code"],
  listCols: l.cols,
  cols: [
    ...l.cols.map((c): [string, ColType, string] => [
      c.column,
      c.type,
      c.column === "code" ? "NOT NULL" : "",
    ]),
    ["sort_order", "int", ""],
  ],
});
LISTS.forEach((l) => ALL.push(list(l)));
for (const t of TABLES) {
  if (!t.headerless) ALL.push(header(t));
  t.children.forEach((c) => ALL.push(child(t, c)));
}
const typ = (x: ColType | "j" | "int") => (x === "int" ? "integer" : x === "j" ? "jsonb" : SQLT[x]);

// Foreign keys to masters (documents point at customers, vendors and roles).
const FKS: [string, string, string, string][] = [];
const fk = (table: string, column: string, ref: string, refCol = "id") =>
  FKS.push([table, column, ref, refCol]);
[
  "customer_contacts",
  "leads",
  "activities",
  "quotations",
  "sales_orders",
  "invoices",
  "installed_machines",
].forEach((t) => fk(t, "customer_id", "customers"));
["purchase_orders", "vendor_bills", "debit_notes", "grns"].forEach((t) =>
  fk(t, "vendor_id", "vendors"),
);
fk("gate_passes", "party_id", "vendors");
fk("staff", "role_id", "roles");

/* ---------------- Table migration ---------------- */
let sql = `-- MEK-SEL ERP: real tables instead of one JSON record store.
-- Generated by scripts/gen-db.ts from src/erp/schema.ts. Do not edit by hand.
--
-- Every kind of record has its own table with real columns, and every list inside a document
-- (quotation lines, PO lines, approval history, ...) has its own line table linked to it with a
-- foreign key (ON DELETE CASCADE). Drop-down lists (units, departments, states, ...) are tables too,
-- edited on the Lists screen. Each row also has:
--   extra       jsonb: anything the app stores that has no column yet (normally empty)
--   sort_order  the record's position in the app's lists
--   updated_at, updated_by  last change (updated_by = staff id | browser tab)
--
-- Security is the same as before: any active staff member can read; changing a table needs full
-- access to one of the modules that work on it (public.erp_write_access) or a matching approval
-- right; deleting documents is for administrators. Realtime is on for every table.
-- The old public.erp_records table is dropped (its data was sample data only).

CREATE OR REPLACE FUNCTION public.erp_touch() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS public.${COUNTERS_TABLE} (
  name text PRIMARY KEY,
  value bigint NOT NULL,
  updated_at timestamptz DEFAULT now(),
  updated_by text
);
COMMENT ON TABLE public.${COUNTERS_TABLE} IS 'Next document numbers (only ever move forward).';
`;
for (const p of ALL) {
  sql += `\nCREATE TABLE IF NOT EXISTS public.${p.name} (\n`;
  const lines = p.cols.map(([c, t, extra]) => `  ${c} ${typ(t)}${extra ? " " + extra : ""}`);
  lines.push(
    "  extra jsonb",
    "  updated_at timestamptz DEFAULT now()",
    "  updated_by text",
    `  PRIMARY KEY (${p.pk.join(", ")})`,
  );
  if (p.parent)
    lines.push(
      `  FOREIGN KEY (${p.parent.col}) REFERENCES public.${p.parent.table} (${p.parent.ref}) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  sql += lines.join(",\n") + "\n);\n";
  sql += `COMMENT ON TABLE public.${p.name} IS ${q(p.doc)};\n`;
  (p.listCols || [])
    .filter((c) => c.label)
    .forEach((c) => (sql += `COMMENT ON COLUMN public.${p.name}.${c.column} IS ${q(c.label)};\n`));
}

sql += `\n-- Documents point at customers, vendors and roles.\n`;
for (const [t, c, ref, rc] of FKS) {
  const name = `${t}_${c}_fkey`;
  sql += `ALTER TABLE public.${t} DROP CONSTRAINT IF EXISTS ${name};\nALTER TABLE public.${t} ADD CONSTRAINT ${name} FOREIGN KEY (${c}) REFERENCES public.${ref} (${rc}) ON UPDATE CASCADE;\nCREATE INDEX IF NOT EXISTS ${t}_${c}_idx ON public.${t} (${c});\n`;
}

const lists = LISTS.map(
  (l) => `  (${q(l.coll)}, '{${l.modules.join(",")}}', '{}', false, false)`,
).join(",\n");
sql += `
-- Who may change the drop-down lists (the other collections were set up by the module rules migration).
INSERT INTO public.erp_write_access (collection, modules, approvals, any_staff, can_delete) VALUES
${lists}
ON CONFLICT (collection) DO UPDATE SET modules = EXCLUDED.modules, approvals = EXCLUDED.approvals, any_staff = EXCLUDED.any_staff, can_delete = EXCLUDED.can_delete;

-- The caller's staff record and role, now read from the staff and role tables.
CREATE OR REPLACE FUNCTION public.erp_me()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'active', coalesce(s.active, false),
    'perms', coalesce((SELECT jsonb_object_agg(p.module, p.access) FROM public.role_permissions p WHERE p.role_id = s.role_id), '{}'::jsonb),
    'approvals', coalesce((SELECT jsonb_object_agg(a.approval, a.allowed) FROM public.role_approvals a WHERE a.role_id = s.role_id), '{}'::jsonb))
  FROM public.staff s
  WHERE s.id = auth.jwt() -> 'app_metadata' ->> 'staff_id'
$$;

-- True while there are no staff records yet (first run, or right after a reset).
CREATE OR REPLACE FUNCTION public.erp_store_empty()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT NOT EXISTS (SELECT 1 FROM public.staff)
$$;

CREATE OR REPLACE FUNCTION public.erp_is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce((SELECT (me ->> 'active')::boolean AND me -> 'perms' ->> 'staff' = 'full' AND me -> 'perms' ->> 'roles' = 'full'
                   FROM public.erp_me() me), false)
$$;

CREATE OR REPLACE FUNCTION public.erp_can_read()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.erp_is_staff() AND (public.erp_store_empty() OR coalesce((public.erp_me() ->> 'active')::boolean, false))
$$;

CREATE OR REPLACE FUNCTION public.erp_can_write(coll text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE
    WHEN NOT public.erp_is_staff() THEN false
    WHEN public.erp_store_empty() THEN true
    ELSE coalesce((
      SELECT (me ->> 'active')::boolean AND (
        a.any_staff
        OR EXISTS (SELECT 1 FROM unnest(a.modules) m WHERE me -> 'perms' ->> m = 'full')
        OR EXISTS (SELECT 1 FROM unnest(a.approvals) k WHERE coalesce((me -> 'approvals' ->> k)::boolean, false)))
      FROM public.erp_write_access a, public.erp_me() me
      WHERE a.collection = coll), false)
  END
$$;

CREATE OR REPLACE FUNCTION public.erp_can_delete(coll text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.erp_can_write(coll) AND (
    public.erp_store_empty()
    OR coalesce((SELECT a.can_delete FROM public.erp_write_access a WHERE a.collection = coll), false)
    OR public.erp_is_admin())
$$;

REVOKE ALL ON FUNCTION public.erp_me() FROM anon;
REVOKE ALL ON FUNCTION public.erp_is_admin() FROM anon;
REVOKE ALL ON FUNCTION public.erp_store_empty() FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_read() FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_write(text) FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_delete(text) FROM anon;
INSERT INTO public.erp_write_access (collection, modules, approvals, any_staff, can_delete) VALUES ('${COUNTERS_TABLE}', '{}', '{}', true, false)
ON CONFLICT (collection) DO UPDATE SET any_staff = true;
`;

// Row-level security, grants, updated_at trigger and Realtime for every table, in one loop.
// Each table is listed with the collection whose module rule applies to it.
const pairs = [[COUNTERS_TABLE, COUNTERS_TABLE], ...ALL.map((p) => [p.name, p.coll])];
sql += `
-- Row-level security, grants, the updated_at trigger and Realtime for every table.
-- Each table is checked against the module rule of its collection (column 2).
DO $sec$
DECLARE t text; c text;
BEGIN
  FOR t, c IN SELECT * FROM (VALUES
${pairs.map(([t, c]) => `    (${q(t)}, ${q(c)})`).join(",\n")}
  ) AS v(t, c) LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: read" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: insert" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: update" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: delete" ON public.%I', t);
    EXECUTE format('CREATE POLICY "ERP staff: read" ON public.%I FOR SELECT TO authenticated USING ((SELECT public.erp_can_read()))', t);
    EXECUTE format('CREATE POLICY "ERP staff: insert" ON public.%I FOR INSERT TO authenticated WITH CHECK ((SELECT public.erp_can_write(%L)))', t, c);
    EXECUTE format('CREATE POLICY "ERP staff: update" ON public.%I FOR UPDATE TO authenticated USING ((SELECT public.erp_can_write(%L))) WITH CHECK ((SELECT public.erp_can_write(%L)))', t, c, c);
    EXECUTE format('CREATE POLICY "ERP staff: delete" ON public.%I FOR DELETE TO authenticated USING ((SELECT public.erp_can_delete(%L)))', t, c);
    EXECUTE format('DROP TRIGGER IF EXISTS erp_touch ON public.%I', t);
    EXECUTE format('CREATE TRIGGER erp_touch BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.erp_touch()', t);
    EXECUTE format('ALTER TABLE public.%I REPLICA IDENTITY FULL', t);
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
       AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END $sec$;
`;

// Sample-data loader: used by the app on an empty database and by "Reset demo data".
const order = [COUNTERS_TABLE, ...ALL.map((p) => p.name)];
const colList = (p: Phys) => [...p.cols.map((c) => c[0]), "extra", "updated_by"].join(", ");
sql += `
-- Loads the sample data sent by the app ({table: rows[]}) in one transaction.
-- Allowed on an empty database for any staff member, or for an administrator with wipe = true
-- (Reset demo data), which first empties every ERP table.
CREATE OR REPLACE FUNCTION public.erp_load_sample(payload jsonb, wipe boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.erp_is_staff() THEN RAISE EXCEPTION 'Sign in as a staff member first.' USING ERRCODE = '42501'; END IF;
  IF wipe THEN
    IF NOT public.erp_is_admin() THEN RAISE EXCEPTION 'Only an administrator can reset the data.' USING ERRCODE = '42501'; END IF;
    TRUNCATE ${order.map((t) => "public." + t).join(", ")} CASCADE;
  ELSIF NOT public.erp_store_empty() THEN
    RAISE EXCEPTION 'The database already has data.' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.${COUNTERS_TABLE} (name, value, updated_by)
    SELECT name, value, updated_by FROM jsonb_populate_recordset(NULL::public.${COUNTERS_TABLE}, payload -> '${COUNTERS_TABLE}')
    ON CONFLICT (name) DO UPDATE SET value = greatest(${COUNTERS_TABLE}.value, EXCLUDED.value);
${ALL.map((p) => `  INSERT INTO public.${p.name} (${colList(p)})\n    SELECT ${colList(p)} FROM jsonb_populate_recordset(NULL::public.${p.name}, payload -> '${p.name}');`).join("\n")}
END $$;
REVOKE ALL ON FUNCTION public.erp_load_sample(jsonb, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.erp_load_sample(jsonb, boolean) TO authenticated;

-- The JSON record store of phases 2 and 3 is replaced by the tables above.
DROP TABLE IF EXISTS public.erp_records CASCADE;
DROP FUNCTION IF EXISTS public.erp_records_touch() CASCADE;
`;
writeFileSync(TABLES_FILE, sql);

/* ---------------- Sample data ---------------- */
const rows = sampleRows();
let seed = `-- MEK-SEL ERP sample data: a working set of customers, products, BOMs, orders, purchases and stock,
-- so every table has rows to look at and edit. Generated by scripts/gen-db.ts from src/erp/engine.ts.
-- Only loaded into an empty database (no staff yet), so it never overwrites real data.
DO $seed$
BEGIN
IF EXISTS (SELECT 1 FROM public.staff) THEN RETURN; END IF;
`;
const meta: Record<string, Phys> = Object.fromEntries(ALL.map((p) => [p.name, p]));
seed += `INSERT INTO public.${COUNTERS_TABLE} (name, value) VALUES\n${rows[COUNTERS_TABLE].map((r) => `  (${q(r.name)}, ${r.value})`).join(",\n")}\nON CONFLICT (name) DO NOTHING;\n`;
for (const p of ALL) {
  const rs = rows[p.name] || [];
  if (!rs.length) continue;
  const cs = [...p.cols.map((c) => c), ["extra", "j", ""] as [string, "j", string]];
  seed += `INSERT INTO public.${p.name} (${cs.map((c) => c[0]).join(", ")}) VALUES\n`;
  seed += rs
    .map(
      (r) =>
        "  (" +
        cs.map(([c, t]) => lit(r[c], t === "int" ? undefined : (t as any))).join(", ") +
        ")",
    )
    .join(",\n");
  seed += "\nON CONFLICT DO NOTHING;\n";
}
seed += "END $seed$;\n";
writeFileSync(SAMPLE_FILE, seed);
console.log(
  `wrote ${TABLES_FILE} (${ALL.length + 1} tables) and ${SAMPLE_FILE} (${Object.values(rows).reduce((s, r) => s + r.length, 0)} rows)`,
);
void meta;
