-- MEK-SEL ERP: real tables instead of one JSON record store.
-- Generated by scripts/gen-db.ts from src/erp/schema.ts. Do not edit by hand.
--
-- Every kind of record has its own table with real columns, and every list inside a document
-- (quotation lines, PO lines, approval history, ...) has its own line table linked to it with a
-- foreign key (ON DELETE CASCADE). Drop-down lists (units, departments, states, ...) are tables too,
-- edited on the Lists screen. Each row also has:
--   extra       jsonb: anything the app stores that has no column yet (normally empty)
--   sort_order  the record's position in the app's lists
--   updated_at, updated_by  last change (updated_by = staff id | browser tab)
--
-- Security is the same as before: any active staff member can read; changing a table needs full
-- access to one of the modules that work on it (public.erp_write_access) or a matching approval
-- right; deleting documents is for administrators. Realtime is on for every table.
-- The old public.erp_records table is dropped (its data was sample data only).

CREATE OR REPLACE FUNCTION public.erp_touch() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS public.doc_counters (
  name text PRIMARY KEY,
  value bigint NOT NULL,
  updated_at timestamptz DEFAULT now(),
  updated_by text
);
COMMENT ON TABLE public.doc_counters IS 'Next document numbers (only ever move forward).';

CREATE TABLE IF NOT EXISTS public.material_categories (
  code text NOT NULL,
  name text,
  bin text,
  lead_days numeric,
  vendor_id text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.material_categories IS 'Raw material categories with their default store, lead time and vendor.';
COMMENT ON COLUMN public.material_categories.code IS 'Code';
COMMENT ON COLUMN public.material_categories.name IS 'Category';
COMMENT ON COLUMN public.material_categories.bin IS 'Store location';
COMMENT ON COLUMN public.material_categories.lead_days IS 'Lead time (days)';
COMMENT ON COLUMN public.material_categories.vendor_id IS 'Default vendor';

CREATE TABLE IF NOT EXISTS public.uoms (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.uoms IS 'Stock units for raw materials.';
COMMENT ON COLUMN public.uoms.code IS 'Code';
COMMENT ON COLUMN public.uoms.name IS 'Unit';

CREATE TABLE IF NOT EXISTS public.lead_sources (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.lead_sources IS 'Where enquiries come from.';
COMMENT ON COLUMN public.lead_sources.code IS 'Code';
COMMENT ON COLUMN public.lead_sources.name IS 'Source';

CREATE TABLE IF NOT EXISTS public.lead_stages (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.lead_stages IS 'Stages on the lead board. New, Quoted, Won and Lost drive the workflow.';
COMMENT ON COLUMN public.lead_stages.code IS 'Code';
COMMENT ON COLUMN public.lead_stages.name IS 'Stage';

CREATE TABLE IF NOT EXISTS public.activity_types (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.activity_types IS 'Kinds of CRM activity.';
COMMENT ON COLUMN public.activity_types.code IS 'Code';
COMMENT ON COLUMN public.activity_types.name IS 'Activity type';

CREATE TABLE IF NOT EXISTS public.contact_roles (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.contact_roles IS 'Role of a customer contact in buying.';
COMMENT ON COLUMN public.contact_roles.code IS 'Code';
COMMENT ON COLUMN public.contact_roles.name IS 'Contact role';

CREATE TABLE IF NOT EXISTS public.departments (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.departments IS 'Departments for staff and indents.';
COMMENT ON COLUMN public.departments.code IS 'Code';
COMMENT ON COLUMN public.departments.name IS 'Department';

CREATE TABLE IF NOT EXISTS public.designations (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.designations IS 'Job titles offered in the staff form.';
COMMENT ON COLUMN public.designations.code IS 'Code';
COMMENT ON COLUMN public.designations.name IS 'Designation';

CREATE TABLE IF NOT EXISTS public.states (
  code text NOT NULL,
  name text,
  gst_code text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.states IS 'Indian states with their GST state codes.';
COMMENT ON COLUMN public.states.code IS 'Code';
COMMENT ON COLUMN public.states.name IS 'State';
COMMENT ON COLUMN public.states.gst_code IS 'GST code';

CREATE TABLE IF NOT EXISTS public.company (
  code text NOT NULL,
  name text,
  address text,
  state text,
  state_code text,
  gstin text,
  gst_rate numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.company IS 'Name, address and GSTIN printed on invoices and POs.';
COMMENT ON COLUMN public.company.code IS 'Code';
COMMENT ON COLUMN public.company.name IS 'Company name';
COMMENT ON COLUMN public.company.address IS 'Address';
COMMENT ON COLUMN public.company.state IS 'State';
COMMENT ON COLUMN public.company.state_code IS 'GST state code';
COMMENT ON COLUMN public.company.gstin IS 'GSTIN';
COMMENT ON COLUMN public.company.gst_rate IS 'GST rate (%)';

CREATE TABLE IF NOT EXISTS public.product_families (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.product_families IS 'Families for finished goods and child items.';
COMMENT ON COLUMN public.product_families.code IS 'Code';
COMMENT ON COLUMN public.product_families.name IS 'Family';

CREATE TABLE IF NOT EXISTS public.bom_groups (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.bom_groups IS 'Sub-assemblies used to group BOM lines.';
COMMENT ON COLUMN public.bom_groups.code IS 'Code';
COMMENT ON COLUMN public.bom_groups.name IS 'Group';

CREATE TABLE IF NOT EXISTS public.item_kinds (
  code text NOT NULL,
  name text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.item_kinds IS 'Kinds of sellable item. Machine and change part drive work orders.';
COMMENT ON COLUMN public.item_kinds.code IS 'Code';
COMMENT ON COLUMN public.item_kinds.name IS 'Label';

CREATE TABLE IF NOT EXISTS public.roles (
  id text NOT NULL,
  name text,
  description text,
  is_system boolean,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.roles IS 'Role master: what each role may see, change and approve.';

CREATE TABLE IF NOT EXISTS public.role_permissions (
  role_id text NOT NULL,
  module text NOT NULL,
  line_no integer NOT NULL,
  access text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (role_id, module),
  FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.role_permissions IS 'Access per module: none, view or full.';

CREATE TABLE IF NOT EXISTS public.role_approvals (
  role_id text NOT NULL,
  approval text NOT NULL,
  line_no integer NOT NULL,
  allowed boolean,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (role_id, approval),
  FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.role_approvals IS 'Approval rights of the role.';

CREATE TABLE IF NOT EXISTS public.staff (
  id text NOT NULL,
  employee_code text,
  name text,
  designation text,
  department text,
  role_id text,
  mobile text,
  email text,
  date_joined date,
  username text,
  active boolean,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.staff IS 'Staff master. Logins are Lovable Cloud accounts linked by staff id.';

CREATE TABLE IF NOT EXISTS public.customers (
  id text NOT NULL,
  name text,
  city text,
  country text,
  state text,
  gstin text,
  address text,
  contact text,
  credit_days numeric,
  credit_limit numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.customers IS 'Customer master.';

CREATE TABLE IF NOT EXISTS public.customer_contacts (
  id text NOT NULL,
  customer_id text,
  name text,
  designation text,
  contact_role text,
  mobile text,
  email text,
  is_primary boolean,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.customer_contacts IS 'People at each customer.';

CREATE TABLE IF NOT EXISTS public.leads (
  id text NOT NULL,
  customer_id text,
  item_code text,
  qty numeric,
  source text,
  stage text,
  follow_up_on timestamptz,
  note text,
  value numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.leads IS 'Sales leads (enquiries).';

CREATE TABLE IF NOT EXISTS public.activities (
  id text NOT NULL,
  activity_type text,
  status text,
  customer_id text,
  contact_id text,
  reference text,
  subject text,
  notes text,
  outcome text,
  done_on timestamptz,
  due_on timestamptz,
  owner_id text,
  promise_date timestamptz,
  promise_amount numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.activities IS 'CRM activities: calls, visits, e-mails and open follow-ups.';

CREATE TABLE IF NOT EXISTS public.quotations (
  id text NOT NULL,
  customer_id text,
  quote_date timestamptz,
  prepared_by text,
  discount_pct numeric,
  status text,
  lead_id text,
  sales_order_id text,
  dropped_standard_items text[],
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.quotations IS 'Quotations with discount approval.';

CREATE TABLE IF NOT EXISTS public.quotation_lines (
  quotation_id text NOT NULL,
  line_no integer NOT NULL,
  item_code text,
  qty numeric,
  price numeric,
  list_price numeric,
  parent_line integer,
  price_included boolean,
  standard_scope boolean,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (quotation_id, line_no),
  FOREIGN KEY (quotation_id) REFERENCES public.quotations (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.quotation_lines IS 'Items quoted. Child items point to their main item with parent_line.';

CREATE TABLE IF NOT EXISTS public.quotation_history (
  quotation_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (quotation_id, line_no),
  FOREIGN KEY (quotation_id) REFERENCES public.quotations (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.quotation_history IS 'Approval trail of the quotation.';

CREATE TABLE IF NOT EXISTS public.sales_orders (
  id text NOT NULL,
  customer_id text,
  order_date timestamptz,
  due_date timestamptz,
  discount_pct numeric,
  advance_received boolean,
  advance_amount numeric,
  advance_pct numeric,
  dispatched boolean,
  dispatched_on timestamptz,
  customer_po text,
  customer_po_date timestamptz,
  on_credit boolean,
  quotation_id text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.sales_orders IS 'Sales orders from customer POs.';

CREATE TABLE IF NOT EXISTS public.sales_order_lines (
  sales_order_id text NOT NULL,
  line_no integer NOT NULL,
  item_code text,
  qty numeric,
  price numeric,
  dispatched_qty numeric,
  list_price numeric,
  parent_line integer,
  price_included boolean,
  standard_scope boolean,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (sales_order_id, line_no),
  FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.sales_order_lines IS 'Items ordered and how many have been dispatched.';

CREATE TABLE IF NOT EXISTS public.sales_order_payments (
  sales_order_id text NOT NULL,
  line_no integer NOT NULL,
  paid_on timestamptz,
  amount numeric,
  mode text,
  reference text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (sales_order_id, line_no),
  FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.sales_order_payments IS 'Advance payments received against the order.';

CREATE TABLE IF NOT EXISTS public.invoices (
  id text NOT NULL,
  invoice_date timestamptz,
  due_date timestamptz,
  sales_order_id text,
  customer_id text,
  customer_po text,
  supply_type text,
  taxable numeric,
  cgst numeric,
  sgst numeric,
  igst numeric,
  tax numeric,
  round_off numeric,
  total numeric,
  advance_adjusted numeric,
  delivery_challan_id text,
  vehicle text,
  transporter text,
  lr_number text,
  eway_bill text,
  shipping_bill text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.invoices IS 'GST tax invoices raised at dispatch.';

CREATE TABLE IF NOT EXISTS public.invoice_lines (
  invoice_id text NOT NULL,
  line_no integer NOT NULL,
  item_code text,
  hsn text,
  qty numeric,
  list_price numeric,
  discount_pct numeric,
  rate numeric,
  taxable numeric,
  price_included boolean,
  is_child_item boolean,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (invoice_id, line_no),
  FOREIGN KEY (invoice_id) REFERENCES public.invoices (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.invoice_lines IS 'Invoiced items.';

CREATE TABLE IF NOT EXISTS public.invoice_payments (
  invoice_id text NOT NULL,
  line_no integer NOT NULL,
  paid_on timestamptz,
  amount numeric,
  mode text,
  reference text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (invoice_id, line_no),
  FOREIGN KEY (invoice_id) REFERENCES public.invoices (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.invoice_payments IS 'Customer payments against the invoice.';

CREATE TABLE IF NOT EXISTS public.delivery_challans (
  id text NOT NULL,
  dc_date timestamptz,
  sales_order_id text,
  invoice_id text,
  vehicle text,
  transporter text,
  lr_number text,
  eway_bill text,
  shipping_bill text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.delivery_challans IS 'Delivery challans (dispatches).';

CREATE TABLE IF NOT EXISTS public.delivery_challan_lines (
  delivery_challan_id text NOT NULL,
  line_no integer NOT NULL,
  item_code text,
  qty numeric,
  order_line integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (delivery_challan_id, line_no),
  FOREIGN KEY (delivery_challan_id) REFERENCES public.delivery_challans (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.delivery_challan_lines IS 'Items dispatched.';

CREATE TABLE IF NOT EXISTS public.installed_machines (
  serial_no text NOT NULL,
  item_code text,
  customer_id text,
  installed_on timestamptz,
  amc_until timestamptz,
  under_warranty boolean,
  installation_pending boolean,
  sales_order_id text,
  delivery_challan_id text,
  engineer_id text,
  operators_trained boolean,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (serial_no)
);
COMMENT ON TABLE public.installed_machines IS 'Machines installed at customers, with warranty and AMC.';

CREATE TABLE IF NOT EXISTS public.service_tickets (
  id text NOT NULL,
  serial_no text,
  issue text,
  opened_on timestamptz,
  status text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.service_tickets IS 'Service calls on installed machines.';

CREATE TABLE IF NOT EXISTS public.products (
  code text NOT NULL,
  name text,
  family text,
  sub_family text,
  kind text,
  price numeric,
  hsn text,
  url text,
  note text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.products IS 'Finished goods: machines and change parts.';

CREATE TABLE IF NOT EXISTS public.product_specs (
  product_code text NOT NULL,
  line_no integer NOT NULL,
  label text,
  value text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code, line_no),
  FOREIGN KEY (product_code) REFERENCES public.products (code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.product_specs IS 'Published specifications.';

CREATE TABLE IF NOT EXISTS public.child_items (
  code text NOT NULL,
  name text,
  family text,
  kind text,
  source text,
  price numeric,
  hsn text,
  description text,
  url text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.child_items IS 'Spares, accessories, documents and services sold with a main item.';

CREATE TABLE IF NOT EXISTS public.child_item_specs (
  child_item_code text NOT NULL,
  line_no integer NOT NULL,
  label text,
  value text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (child_item_code, line_no),
  FOREIGN KEY (child_item_code) REFERENCES public.child_items (code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.child_item_specs IS 'Specifications.';

CREATE TABLE IF NOT EXISTS public.materials (
  code text NOT NULL,
  name text,
  category_id integer,
  uom text,
  rate numeric,
  on_hand numeric,
  reorder_level numeric,
  max_level numeric,
  lead_days numeric,
  bin text,
  vendor_id text,
  is_job_work boolean,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (code)
);
COMMENT ON TABLE public.materials IS 'Raw material master with stock levels.';

CREATE TABLE IF NOT EXISTS public.material_units (
  material_code text NOT NULL,
  line_no integer NOT NULL,
  unit text,
  factor numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (material_code, line_no),
  FOREIGN KEY (material_code) REFERENCES public.materials (code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.material_units IS 'Alternative units: 1 unit = factor × base unit.';

CREATE TABLE IF NOT EXISTS public.boms (
  product_code text NOT NULL,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code)
);
COMMENT ON TABLE public.boms IS 'Bill of materials header (one per product).';

CREATE TABLE IF NOT EXISTS public.bom_lines (
  product_code text NOT NULL,
  line_no integer NOT NULL,
  group_name text,
  material_code text,
  qty numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code, line_no),
  FOREIGN KEY (product_code) REFERENCES public.boms (product_code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.bom_lines IS 'Material per sub-assembly for one product.';

CREATE TABLE IF NOT EXISTS public.bom_versions (
  product_code text NOT NULL,
  line_no integer NOT NULL,
  version integer,
  released_at timestamptz,
  released_by text,
  note text,
  line_count integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code, line_no)
);
COMMENT ON TABLE public.bom_versions IS 'One row per BOM release.';

CREATE TABLE IF NOT EXISTS public.combo_sets (
  product_code text NOT NULL,
  revision integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code)
);
COMMENT ON TABLE public.combo_sets IS 'Combo set: the standard and optional scope sold with a main item.';

CREATE TABLE IF NOT EXISTS public.combo_set_lines (
  product_code text NOT NULL,
  line_no integer NOT NULL,
  item_code text,
  qty numeric,
  standard_scope numeric,
  price_included numeric,
  note text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code, line_no),
  FOREIGN KEY (product_code) REFERENCES public.combo_sets (product_code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.combo_set_lines IS 'Child items of the set. 1 = yes, 0 = no.';

CREATE TABLE IF NOT EXISTS public.combo_set_history (
  product_code text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  by_staff_id text,
  note text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (product_code, line_no),
  FOREIGN KEY (product_code) REFERENCES public.combo_sets (product_code) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.combo_set_history IS 'Changes to the set.';

CREATE TABLE IF NOT EXISTS public.work_orders (
  id text NOT NULL,
  sales_order_id text,
  item_code text,
  qty numeric,
  stage integer,
  material_issued boolean,
  order_line integer,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.work_orders IS 'Work orders for machines and change parts.';

CREATE TABLE IF NOT EXISTS public.vendors (
  id text NOT NULL,
  name text,
  city text,
  supplies text,
  state text,
  gstin text,
  contact text,
  phone text,
  email text,
  payment_terms_days numeric,
  active boolean,
  is_msme boolean,
  udyam_no text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.vendors IS 'Vendor master.';

CREATE TABLE IF NOT EXISTS public.indents (
  id text NOT NULL,
  indent_date timestamptz,
  raised_by text,
  department text,
  source text,
  need_by timestamptz,
  reason text,
  status text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.indents IS 'Purchase indents (requests to buy).';

CREATE TABLE IF NOT EXISTS public.indent_lines (
  indent_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  qty numeric,
  approved_qty numeric,
  ordered_qty numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (indent_id, line_no),
  FOREIGN KEY (indent_id) REFERENCES public.indents (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.indent_lines IS 'Materials requested.';

CREATE TABLE IF NOT EXISTS public.indent_history (
  indent_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (indent_id, line_no),
  FOREIGN KEY (indent_id) REFERENCES public.indents (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.indent_history IS 'Approval trail of the indent.';

CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id text NOT NULL,
  po_date timestamptz,
  vendor_id text,
  indent_id text,
  due_date timestamptz,
  status text,
  reason text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.purchase_orders IS 'Purchase orders to vendors.';

CREATE TABLE IF NOT EXISTS public.purchase_order_lines (
  purchase_order_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  qty numeric,
  rate numeric,
  received_qty numeric,
  rejected_qty numeric,
  order_unit text,
  unit_factor numeric,
  order_qty numeric,
  order_rate numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (purchase_order_id, line_no),
  FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.purchase_order_lines IS 'Materials ordered (qty and rate in stock units; order_* in the unit ordered).';

CREATE TABLE IF NOT EXISTS public.purchase_order_history (
  purchase_order_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (purchase_order_id, line_no),
  FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.purchase_order_history IS 'Approval trail of the PO.';

CREATE TABLE IF NOT EXISTS public.gate_passes (
  id text NOT NULL,
  direction text,
  pass_date timestamptz,
  purchase_order_id text,
  party_id text,
  vehicle text,
  party_document text,
  status text,
  grn_id text,
  returnable boolean,
  purpose text,
  expected_back timestamptz,
  reference text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.gate_passes IS 'Gate entries (in) and gate passes (out).';

CREATE TABLE IF NOT EXISTS public.gate_pass_lines (
  gate_pass_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  qty numeric,
  returned_qty numeric,
  rejected_at_gate numeric,
  rejection_reason text,
  arrived_unit text,
  arrived_unit_qty numeric,
  rejected_unit_qty numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (gate_pass_id, line_no),
  FOREIGN KEY (gate_pass_id) REFERENCES public.gate_passes (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.gate_pass_lines IS 'Material through the gate.';

CREATE TABLE IF NOT EXISTS public.gate_pass_history (
  gate_pass_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (gate_pass_id, line_no),
  FOREIGN KEY (gate_pass_id) REFERENCES public.gate_passes (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.gate_pass_history IS 'Trail of the gate entry or pass.';

CREATE TABLE IF NOT EXISTS public.grns (
  id text NOT NULL,
  grn_date timestamptz,
  gate_entry_id text,
  purchase_order_id text,
  vendor_id text,
  received_by text,
  status text,
  return_pass_id text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.grns IS 'Goods receipt notes with QC acceptance.';

CREATE TABLE IF NOT EXISTS public.grn_lines (
  grn_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  received_qty numeric,
  accepted_qty numeric,
  rejected_qty numeric,
  rejection_reason text,
  billed_qty numeric,
  counted_qty numeric,
  counted_unit text,
  theoretical_qty numeric,
  weighed_kg numeric,
  weight_variance_pct numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (grn_id, line_no),
  FOREIGN KEY (grn_id) REFERENCES public.grns (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.grn_lines IS 'Material received and inspected.';

CREATE TABLE IF NOT EXISTS public.grn_history (
  grn_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (grn_id, line_no),
  FOREIGN KEY (grn_id) REFERENCES public.grns (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.grn_history IS 'QC trail of the GRN.';

CREATE TABLE IF NOT EXISTS public.vendor_bills (
  id text NOT NULL,
  vendor_invoice_no text,
  vendor_invoice_date timestamptz,
  booked_on timestamptz,
  vendor_id text,
  grn_id text,
  purchase_order_id text,
  status text,
  match_status text,
  approved_total numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.vendor_bills IS 'Vendor bills with 3-way match.';

CREATE TABLE IF NOT EXISTS public.vendor_bill_lines (
  vendor_bill_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  qty numeric,
  rate numeric,
  po_rate numeric,
  accepted_qty numeric,
  billed_amount numeric,
  billed_unit text,
  billed_unit_qty numeric,
  billed_unit_rate numeric,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (vendor_bill_id, line_no),
  FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.vendor_bill_lines IS 'Billed materials.';

CREATE TABLE IF NOT EXISTS public.vendor_bill_payments (
  vendor_bill_id text NOT NULL,
  line_no integer NOT NULL,
  paid_on timestamptz,
  amount numeric,
  mode text,
  reference text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (vendor_bill_id, line_no),
  FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.vendor_bill_payments IS 'Payments to the vendor.';

CREATE TABLE IF NOT EXISTS public.vendor_bill_history (
  vendor_bill_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (vendor_bill_id, line_no),
  FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.vendor_bill_history IS 'Trail of the bill.';

CREATE TABLE IF NOT EXISTS public.debit_notes (
  id text NOT NULL,
  note_date timestamptz,
  vendor_id text,
  vendor_bill_id text,
  reason text,
  taxable numeric,
  tax numeric,
  total numeric,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.debit_notes IS 'Debit notes raised on vendors.';

CREATE TABLE IF NOT EXISTS public.material_requisitions (
  id text NOT NULL,
  requested_on timestamptz,
  requested_by text,
  work_order_id text,
  purpose text,
  status text,
  previous_status text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.material_requisitions IS 'Material requisitions from the shop floor.';

CREATE TABLE IF NOT EXISTS public.material_requisition_lines (
  material_requisition_id text NOT NULL,
  line_no integer NOT NULL,
  material_code text,
  qty numeric,
  approved_qty numeric,
  issued_qty numeric,
  received_qty numeric,
  returned_qty numeric,
  return_reason text,
  indent_id text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (material_requisition_id, line_no),
  FOREIGN KEY (material_requisition_id) REFERENCES public.material_requisitions (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.material_requisition_lines IS 'Materials requested, approved, issued and confirmed.';

CREATE TABLE IF NOT EXISTS public.material_requisition_history (
  material_requisition_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (material_requisition_id, line_no),
  FOREIGN KEY (material_requisition_id) REFERENCES public.material_requisitions (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.material_requisition_history IS 'Approval and issue trail.';

CREATE TABLE IF NOT EXISTS public.stock_ledger (
  id text NOT NULL,
  posted_at timestamptz,
  posted_time text,
  material_code text,
  movement_type text,
  reference text,
  qty_in numeric,
  qty_out numeric,
  balance numeric,
  posted_by text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.stock_ledger IS 'Every stock movement with the running balance.';

CREATE TABLE IF NOT EXISTS public.stock_adjustments (
  id text NOT NULL,
  adjusted_on timestamptz,
  raised_by text,
  material_code text,
  system_qty numeric,
  counted_qty numeric,
  reason text,
  status text,
  sort_order integer,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (id)
);
COMMENT ON TABLE public.stock_adjustments IS 'Stock adjustments after a physical count.';

CREATE TABLE IF NOT EXISTS public.stock_adjustment_history (
  stock_adjustment_id text NOT NULL,
  line_no integer NOT NULL,
  at timestamptz,
  at_time text,
  by_staff_id text,
  action text,
  note text,
  tone text,
  extra jsonb,
  updated_at timestamptz DEFAULT now(),
  updated_by text,
  PRIMARY KEY (stock_adjustment_id, line_no),
  FOREIGN KEY (stock_adjustment_id) REFERENCES public.stock_adjustments (id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE public.stock_adjustment_history IS 'Approval trail.';

-- Documents point at customers, vendors and roles.
ALTER TABLE public.customer_contacts DROP CONSTRAINT IF EXISTS customer_contacts_customer_id_fkey;
ALTER TABLE public.customer_contacts ADD CONSTRAINT customer_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS customer_contacts_customer_id_idx ON public.customer_contacts (customer_id);
ALTER TABLE public.leads DROP CONSTRAINT IF EXISTS leads_customer_id_fkey;
ALTER TABLE public.leads ADD CONSTRAINT leads_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS leads_customer_id_idx ON public.leads (customer_id);
ALTER TABLE public.activities DROP CONSTRAINT IF EXISTS activities_customer_id_fkey;
ALTER TABLE public.activities ADD CONSTRAINT activities_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS activities_customer_id_idx ON public.activities (customer_id);
ALTER TABLE public.quotations DROP CONSTRAINT IF EXISTS quotations_customer_id_fkey;
ALTER TABLE public.quotations ADD CONSTRAINT quotations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS quotations_customer_id_idx ON public.quotations (customer_id);
ALTER TABLE public.sales_orders DROP CONSTRAINT IF EXISTS sales_orders_customer_id_fkey;
ALTER TABLE public.sales_orders ADD CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS sales_orders_customer_id_idx ON public.sales_orders (customer_id);
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_customer_id_fkey;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS invoices_customer_id_idx ON public.invoices (customer_id);
ALTER TABLE public.installed_machines DROP CONSTRAINT IF EXISTS installed_machines_customer_id_fkey;
ALTER TABLE public.installed_machines ADD CONSTRAINT installed_machines_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS installed_machines_customer_id_idx ON public.installed_machines (customer_id);
ALTER TABLE public.purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_vendor_id_fkey;
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS purchase_orders_vendor_id_idx ON public.purchase_orders (vendor_id);
ALTER TABLE public.vendor_bills DROP CONSTRAINT IF EXISTS vendor_bills_vendor_id_fkey;
ALTER TABLE public.vendor_bills ADD CONSTRAINT vendor_bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS vendor_bills_vendor_id_idx ON public.vendor_bills (vendor_id);
ALTER TABLE public.debit_notes DROP CONSTRAINT IF EXISTS debit_notes_vendor_id_fkey;
ALTER TABLE public.debit_notes ADD CONSTRAINT debit_notes_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS debit_notes_vendor_id_idx ON public.debit_notes (vendor_id);
ALTER TABLE public.grns DROP CONSTRAINT IF EXISTS grns_vendor_id_fkey;
ALTER TABLE public.grns ADD CONSTRAINT grns_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS grns_vendor_id_idx ON public.grns (vendor_id);
ALTER TABLE public.gate_passes DROP CONSTRAINT IF EXISTS gate_passes_party_id_fkey;
ALTER TABLE public.gate_passes ADD CONSTRAINT gate_passes_party_id_fkey FOREIGN KEY (party_id) REFERENCES public.vendors (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS gate_passes_party_id_idx ON public.gate_passes (party_id);
ALTER TABLE public.staff DROP CONSTRAINT IF EXISTS staff_role_id_fkey;
ALTER TABLE public.staff ADD CONSTRAINT staff_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles (id) ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS staff_role_id_idx ON public.staff (role_id);

-- Who may change the drop-down lists (the other collections were set up by the module rules migration).
INSERT INTO public.erp_write_access (collection, modules, approvals, any_staff, can_delete) VALUES
  ('material_categories', '{materials,inventory,stores}', '{}', false, false),
  ('uoms', '{materials,inventory,stores}', '{}', false, false),
  ('lead_sources', '{leads,crm,customers}', '{}', false, false),
  ('lead_stages', '{leads,crm}', '{}', false, false),
  ('activity_types', '{crm,leads}', '{}', false, false),
  ('contact_roles', '{crm,customers,leads}', '{}', false, false),
  ('departments', '{staff,roles}', '{}', false, false),
  ('designations', '{staff,roles}', '{}', false, false),
  ('states', '{staff,roles,customers,vendors}', '{}', false, false),
  ('company', '{staff,roles}', '{}', false, false),
  ('product_families', '{products,combos,bom}', '{}', false, false),
  ('bom_groups', '{bom,products}', '{}', false, false),
  ('item_kinds', '{products,combos,bom}', '{}', false, false)
ON CONFLICT (collection) DO UPDATE SET modules = EXCLUDED.modules, approvals = EXCLUDED.approvals, any_staff = EXCLUDED.any_staff, can_delete = EXCLUDED.can_delete;

-- The caller's staff record and role, now read from the staff and role tables.
CREATE OR REPLACE FUNCTION public.erp_me()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'active', coalesce(s.active, false),
    'perms', coalesce((SELECT jsonb_object_agg(p.module, p.access) FROM public.role_permissions p WHERE p.role_id = s.role_id), '{}'::jsonb),
    'approvals', coalesce((SELECT jsonb_object_agg(a.approval, a.allowed) FROM public.role_approvals a WHERE a.role_id = s.role_id), '{}'::jsonb))
  FROM public.staff s
  WHERE s.id = auth.jwt() -> 'app_metadata' ->> 'staff_id'
$$;

-- True while there are no staff records yet (first run, or right after a reset).
CREATE OR REPLACE FUNCTION public.erp_store_empty()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT NOT EXISTS (SELECT 1 FROM public.staff)
$$;

CREATE OR REPLACE FUNCTION public.erp_is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce((SELECT (me ->> 'active')::boolean AND me -> 'perms' ->> 'staff' = 'full' AND me -> 'perms' ->> 'roles' = 'full'
                   FROM public.erp_me() me), false)
$$;

CREATE OR REPLACE FUNCTION public.erp_can_read()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.erp_is_staff() AND (public.erp_store_empty() OR coalesce((public.erp_me() ->> 'active')::boolean, false))
$$;

CREATE OR REPLACE FUNCTION public.erp_can_write(coll text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE
    WHEN NOT public.erp_is_staff() THEN false
    WHEN public.erp_store_empty() THEN true
    ELSE coalesce((
      SELECT (me ->> 'active')::boolean AND (
        a.any_staff
        OR EXISTS (SELECT 1 FROM unnest(a.modules) m WHERE me -> 'perms' ->> m = 'full')
        OR EXISTS (SELECT 1 FROM unnest(a.approvals) k WHERE coalesce((me -> 'approvals' ->> k)::boolean, false)))
      FROM public.erp_write_access a, public.erp_me() me
      WHERE a.collection = coll), false)
  END
$$;

CREATE OR REPLACE FUNCTION public.erp_can_delete(coll text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.erp_can_write(coll) AND (
    public.erp_store_empty()
    OR coalesce((SELECT a.can_delete FROM public.erp_write_access a WHERE a.collection = coll), false)
    OR public.erp_is_admin())
$$;

REVOKE ALL ON FUNCTION public.erp_me() FROM anon;
REVOKE ALL ON FUNCTION public.erp_is_admin() FROM anon;
REVOKE ALL ON FUNCTION public.erp_store_empty() FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_read() FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_write(text) FROM anon;
REVOKE ALL ON FUNCTION public.erp_can_delete(text) FROM anon;
INSERT INTO public.erp_write_access (collection, modules, approvals, any_staff, can_delete) VALUES ('doc_counters', '{}', '{}', true, false)
ON CONFLICT (collection) DO UPDATE SET any_staff = true;

-- Row-level security, grants, the updated_at trigger and Realtime for every table.
-- Each table is checked against the module rule of its collection (column 2).
DO $sec$
DECLARE t text; c text;
BEGIN
  FOR t, c IN SELECT * FROM (VALUES
    ('doc_counters', 'doc_counters'),
    ('material_categories', 'material_categories'),
    ('uoms', 'uoms'),
    ('lead_sources', 'lead_sources'),
    ('lead_stages', 'lead_stages'),
    ('activity_types', 'activity_types'),
    ('contact_roles', 'contact_roles'),
    ('departments', 'departments'),
    ('designations', 'designations'),
    ('states', 'states'),
    ('company', 'company'),
    ('product_families', 'product_families'),
    ('bom_groups', 'bom_groups'),
    ('item_kinds', 'item_kinds'),
    ('roles', 'roles'),
    ('role_permissions', 'roles'),
    ('role_approvals', 'roles'),
    ('staff', 'staff'),
    ('customers', 'customers'),
    ('customer_contacts', 'contacts'),
    ('leads', 'leads'),
    ('activities', 'activities'),
    ('quotations', 'quotations'),
    ('quotation_lines', 'quotations'),
    ('quotation_history', 'quotations'),
    ('sales_orders', 'sales_orders'),
    ('sales_order_lines', 'sales_orders'),
    ('sales_order_payments', 'sales_orders'),
    ('invoices', 'invoices'),
    ('invoice_lines', 'invoices'),
    ('invoice_payments', 'invoices'),
    ('delivery_challans', 'delivery_challans'),
    ('delivery_challan_lines', 'delivery_challans'),
    ('installed_machines', 'installed_base'),
    ('service_tickets', 'service_tickets'),
    ('products', 'products'),
    ('product_specs', 'products'),
    ('child_items', 'child_items'),
    ('child_item_specs', 'child_items'),
    ('materials', 'materials'),
    ('material_units', 'materials'),
    ('boms', 'bom'),
    ('bom_lines', 'bom'),
    ('bom_versions', 'bom_versions'),
    ('combo_sets', 'combos'),
    ('combo_set_lines', 'combos'),
    ('combo_set_history', 'combos'),
    ('work_orders', 'work_orders'),
    ('vendors', 'vendors'),
    ('indents', 'indents'),
    ('indent_lines', 'indents'),
    ('indent_history', 'indents'),
    ('purchase_orders', 'purchase_orders'),
    ('purchase_order_lines', 'purchase_orders'),
    ('purchase_order_history', 'purchase_orders'),
    ('gate_passes', 'gate_passes'),
    ('gate_pass_lines', 'gate_passes'),
    ('gate_pass_history', 'gate_passes'),
    ('grns', 'grns'),
    ('grn_lines', 'grns'),
    ('grn_history', 'grns'),
    ('vendor_bills', 'vendor_bills'),
    ('vendor_bill_lines', 'vendor_bills'),
    ('vendor_bill_payments', 'vendor_bills'),
    ('vendor_bill_history', 'vendor_bills'),
    ('debit_notes', 'debit_notes'),
    ('material_requisitions', 'requisitions'),
    ('material_requisition_lines', 'requisitions'),
    ('material_requisition_history', 'requisitions'),
    ('stock_ledger', 'stock_ledger'),
    ('stock_adjustments', 'stock_adjustments'),
    ('stock_adjustment_history', 'stock_adjustments')
  ) AS v(t, c) LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: read" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: insert" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: update" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "ERP staff: delete" ON public.%I', t);
    EXECUTE format('CREATE POLICY "ERP staff: read" ON public.%I FOR SELECT TO authenticated USING ((SELECT public.erp_can_read()))', t);
    EXECUTE format('CREATE POLICY "ERP staff: insert" ON public.%I FOR INSERT TO authenticated WITH CHECK ((SELECT public.erp_can_write(%L)))', t, c);
    EXECUTE format('CREATE POLICY "ERP staff: update" ON public.%I FOR UPDATE TO authenticated USING ((SELECT public.erp_can_write(%L))) WITH CHECK ((SELECT public.erp_can_write(%L)))', t, c, c);
    EXECUTE format('CREATE POLICY "ERP staff: delete" ON public.%I FOR DELETE TO authenticated USING ((SELECT public.erp_can_delete(%L)))', t, c);
    EXECUTE format('DROP TRIGGER IF EXISTS erp_touch ON public.%I', t);
    EXECUTE format('CREATE TRIGGER erp_touch BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.erp_touch()', t);
    EXECUTE format('ALTER TABLE public.%I REPLICA IDENTITY FULL', t);
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
       AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END $sec$;

-- Loads the sample data sent by the app ({table: rows[]}) in one transaction.
-- Allowed on an empty database for any staff member, or for an administrator with wipe = true
-- (Reset demo data), which first empties every ERP table.
CREATE OR REPLACE FUNCTION public.erp_load_sample(payload jsonb, wipe boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.erp_is_staff() THEN RAISE EXCEPTION 'Sign in as a staff member first.' USING ERRCODE = '42501'; END IF;
  IF wipe THEN
    IF NOT public.erp_is_admin() THEN RAISE EXCEPTION 'Only an administrator can reset the data.' USING ERRCODE = '42501'; END IF;
    TRUNCATE public.doc_counters, public.material_categories, public.uoms, public.lead_sources, public.lead_stages, public.activity_types, public.contact_roles, public.departments, public.designations, public.states, public.company, public.product_families, public.bom_groups, public.item_kinds, public.roles, public.role_permissions, public.role_approvals, public.staff, public.customers, public.customer_contacts, public.leads, public.activities, public.quotations, public.quotation_lines, public.quotation_history, public.sales_orders, public.sales_order_lines, public.sales_order_payments, public.invoices, public.invoice_lines, public.invoice_payments, public.delivery_challans, public.delivery_challan_lines, public.installed_machines, public.service_tickets, public.products, public.product_specs, public.child_items, public.child_item_specs, public.materials, public.material_units, public.boms, public.bom_lines, public.bom_versions, public.combo_sets, public.combo_set_lines, public.combo_set_history, public.work_orders, public.vendors, public.indents, public.indent_lines, public.indent_history, public.purchase_orders, public.purchase_order_lines, public.purchase_order_history, public.gate_passes, public.gate_pass_lines, public.gate_pass_history, public.grns, public.grn_lines, public.grn_history, public.vendor_bills, public.vendor_bill_lines, public.vendor_bill_payments, public.vendor_bill_history, public.debit_notes, public.material_requisitions, public.material_requisition_lines, public.material_requisition_history, public.stock_ledger, public.stock_adjustments, public.stock_adjustment_history CASCADE;
  ELSIF NOT public.erp_store_empty() THEN
    RAISE EXCEPTION 'The database already has data.' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.doc_counters (name, value, updated_by)
    SELECT name, value, updated_by FROM jsonb_populate_recordset(NULL::public.doc_counters, payload -> 'doc_counters')
    ON CONFLICT (name) DO UPDATE SET value = greatest(doc_counters.value, EXCLUDED.value);
  INSERT INTO public.material_categories (code, name, bin, lead_days, vendor_id, sort_order, extra, updated_by)
    SELECT code, name, bin, lead_days, vendor_id, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.material_categories, payload -> 'material_categories');
  INSERT INTO public.uoms (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.uoms, payload -> 'uoms');
  INSERT INTO public.lead_sources (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.lead_sources, payload -> 'lead_sources');
  INSERT INTO public.lead_stages (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.lead_stages, payload -> 'lead_stages');
  INSERT INTO public.activity_types (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.activity_types, payload -> 'activity_types');
  INSERT INTO public.contact_roles (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.contact_roles, payload -> 'contact_roles');
  INSERT INTO public.departments (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.departments, payload -> 'departments');
  INSERT INTO public.designations (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.designations, payload -> 'designations');
  INSERT INTO public.states (code, name, gst_code, sort_order, extra, updated_by)
    SELECT code, name, gst_code, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.states, payload -> 'states');
  INSERT INTO public.company (code, name, address, state, state_code, gstin, gst_rate, sort_order, extra, updated_by)
    SELECT code, name, address, state, state_code, gstin, gst_rate, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.company, payload -> 'company');
  INSERT INTO public.product_families (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.product_families, payload -> 'product_families');
  INSERT INTO public.bom_groups (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.bom_groups, payload -> 'bom_groups');
  INSERT INTO public.item_kinds (code, name, sort_order, extra, updated_by)
    SELECT code, name, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.item_kinds, payload -> 'item_kinds');
  INSERT INTO public.roles (id, name, description, is_system, sort_order, extra, updated_by)
    SELECT id, name, description, is_system, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.roles, payload -> 'roles');
  INSERT INTO public.role_permissions (role_id, module, line_no, access, extra, updated_by)
    SELECT role_id, module, line_no, access, extra, updated_by FROM jsonb_populate_recordset(NULL::public.role_permissions, payload -> 'role_permissions');
  INSERT INTO public.role_approvals (role_id, approval, line_no, allowed, extra, updated_by)
    SELECT role_id, approval, line_no, allowed, extra, updated_by FROM jsonb_populate_recordset(NULL::public.role_approvals, payload -> 'role_approvals');
  INSERT INTO public.staff (id, employee_code, name, designation, department, role_id, mobile, email, date_joined, username, active, sort_order, extra, updated_by)
    SELECT id, employee_code, name, designation, department, role_id, mobile, email, date_joined, username, active, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.staff, payload -> 'staff');
  INSERT INTO public.customers (id, name, city, country, state, gstin, address, contact, credit_days, credit_limit, sort_order, extra, updated_by)
    SELECT id, name, city, country, state, gstin, address, contact, credit_days, credit_limit, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.customers, payload -> 'customers');
  INSERT INTO public.customer_contacts (id, customer_id, name, designation, contact_role, mobile, email, is_primary, sort_order, extra, updated_by)
    SELECT id, customer_id, name, designation, contact_role, mobile, email, is_primary, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.customer_contacts, payload -> 'customer_contacts');
  INSERT INTO public.leads (id, customer_id, item_code, qty, source, stage, follow_up_on, note, value, sort_order, extra, updated_by)
    SELECT id, customer_id, item_code, qty, source, stage, follow_up_on, note, value, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.leads, payload -> 'leads');
  INSERT INTO public.activities (id, activity_type, status, customer_id, contact_id, reference, subject, notes, outcome, done_on, due_on, owner_id, promise_date, promise_amount, sort_order, extra, updated_by)
    SELECT id, activity_type, status, customer_id, contact_id, reference, subject, notes, outcome, done_on, due_on, owner_id, promise_date, promise_amount, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.activities, payload -> 'activities');
  INSERT INTO public.quotations (id, customer_id, quote_date, prepared_by, discount_pct, status, lead_id, sales_order_id, dropped_standard_items, sort_order, extra, updated_by)
    SELECT id, customer_id, quote_date, prepared_by, discount_pct, status, lead_id, sales_order_id, dropped_standard_items, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.quotations, payload -> 'quotations');
  INSERT INTO public.quotation_lines (quotation_id, line_no, item_code, qty, price, list_price, parent_line, price_included, standard_scope, extra, updated_by)
    SELECT quotation_id, line_no, item_code, qty, price, list_price, parent_line, price_included, standard_scope, extra, updated_by FROM jsonb_populate_recordset(NULL::public.quotation_lines, payload -> 'quotation_lines');
  INSERT INTO public.quotation_history (quotation_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT quotation_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.quotation_history, payload -> 'quotation_history');
  INSERT INTO public.sales_orders (id, customer_id, order_date, due_date, discount_pct, advance_received, advance_amount, advance_pct, dispatched, dispatched_on, customer_po, customer_po_date, on_credit, quotation_id, sort_order, extra, updated_by)
    SELECT id, customer_id, order_date, due_date, discount_pct, advance_received, advance_amount, advance_pct, dispatched, dispatched_on, customer_po, customer_po_date, on_credit, quotation_id, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.sales_orders, payload -> 'sales_orders');
  INSERT INTO public.sales_order_lines (sales_order_id, line_no, item_code, qty, price, dispatched_qty, list_price, parent_line, price_included, standard_scope, extra, updated_by)
    SELECT sales_order_id, line_no, item_code, qty, price, dispatched_qty, list_price, parent_line, price_included, standard_scope, extra, updated_by FROM jsonb_populate_recordset(NULL::public.sales_order_lines, payload -> 'sales_order_lines');
  INSERT INTO public.sales_order_payments (sales_order_id, line_no, paid_on, amount, mode, reference, extra, updated_by)
    SELECT sales_order_id, line_no, paid_on, amount, mode, reference, extra, updated_by FROM jsonb_populate_recordset(NULL::public.sales_order_payments, payload -> 'sales_order_payments');
  INSERT INTO public.invoices (id, invoice_date, due_date, sales_order_id, customer_id, customer_po, supply_type, taxable, cgst, sgst, igst, tax, round_off, total, advance_adjusted, delivery_challan_id, vehicle, transporter, lr_number, eway_bill, shipping_bill, sort_order, extra, updated_by)
    SELECT id, invoice_date, due_date, sales_order_id, customer_id, customer_po, supply_type, taxable, cgst, sgst, igst, tax, round_off, total, advance_adjusted, delivery_challan_id, vehicle, transporter, lr_number, eway_bill, shipping_bill, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.invoices, payload -> 'invoices');
  INSERT INTO public.invoice_lines (invoice_id, line_no, item_code, hsn, qty, list_price, discount_pct, rate, taxable, price_included, is_child_item, extra, updated_by)
    SELECT invoice_id, line_no, item_code, hsn, qty, list_price, discount_pct, rate, taxable, price_included, is_child_item, extra, updated_by FROM jsonb_populate_recordset(NULL::public.invoice_lines, payload -> 'invoice_lines');
  INSERT INTO public.invoice_payments (invoice_id, line_no, paid_on, amount, mode, reference, extra, updated_by)
    SELECT invoice_id, line_no, paid_on, amount, mode, reference, extra, updated_by FROM jsonb_populate_recordset(NULL::public.invoice_payments, payload -> 'invoice_payments');
  INSERT INTO public.delivery_challans (id, dc_date, sales_order_id, invoice_id, vehicle, transporter, lr_number, eway_bill, shipping_bill, sort_order, extra, updated_by)
    SELECT id, dc_date, sales_order_id, invoice_id, vehicle, transporter, lr_number, eway_bill, shipping_bill, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.delivery_challans, payload -> 'delivery_challans');
  INSERT INTO public.delivery_challan_lines (delivery_challan_id, line_no, item_code, qty, order_line, extra, updated_by)
    SELECT delivery_challan_id, line_no, item_code, qty, order_line, extra, updated_by FROM jsonb_populate_recordset(NULL::public.delivery_challan_lines, payload -> 'delivery_challan_lines');
  INSERT INTO public.installed_machines (serial_no, item_code, customer_id, installed_on, amc_until, under_warranty, installation_pending, sales_order_id, delivery_challan_id, engineer_id, operators_trained, sort_order, extra, updated_by)
    SELECT serial_no, item_code, customer_id, installed_on, amc_until, under_warranty, installation_pending, sales_order_id, delivery_challan_id, engineer_id, operators_trained, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.installed_machines, payload -> 'installed_machines');
  INSERT INTO public.service_tickets (id, serial_no, issue, opened_on, status, sort_order, extra, updated_by)
    SELECT id, serial_no, issue, opened_on, status, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.service_tickets, payload -> 'service_tickets');
  INSERT INTO public.products (code, name, family, sub_family, kind, price, hsn, url, note, sort_order, extra, updated_by)
    SELECT code, name, family, sub_family, kind, price, hsn, url, note, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.products, payload -> 'products');
  INSERT INTO public.product_specs (product_code, line_no, label, value, extra, updated_by)
    SELECT product_code, line_no, label, value, extra, updated_by FROM jsonb_populate_recordset(NULL::public.product_specs, payload -> 'product_specs');
  INSERT INTO public.child_items (code, name, family, kind, source, price, hsn, description, url, sort_order, extra, updated_by)
    SELECT code, name, family, kind, source, price, hsn, description, url, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.child_items, payload -> 'child_items');
  INSERT INTO public.child_item_specs (child_item_code, line_no, label, value, extra, updated_by)
    SELECT child_item_code, line_no, label, value, extra, updated_by FROM jsonb_populate_recordset(NULL::public.child_item_specs, payload -> 'child_item_specs');
  INSERT INTO public.materials (code, name, category_id, uom, rate, on_hand, reorder_level, max_level, lead_days, bin, vendor_id, is_job_work, sort_order, extra, updated_by)
    SELECT code, name, category_id, uom, rate, on_hand, reorder_level, max_level, lead_days, bin, vendor_id, is_job_work, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.materials, payload -> 'materials');
  INSERT INTO public.material_units (material_code, line_no, unit, factor, extra, updated_by)
    SELECT material_code, line_no, unit, factor, extra, updated_by FROM jsonb_populate_recordset(NULL::public.material_units, payload -> 'material_units');
  INSERT INTO public.boms (product_code, extra, updated_by)
    SELECT product_code, extra, updated_by FROM jsonb_populate_recordset(NULL::public.boms, payload -> 'boms');
  INSERT INTO public.bom_lines (product_code, line_no, group_name, material_code, qty, extra, updated_by)
    SELECT product_code, line_no, group_name, material_code, qty, extra, updated_by FROM jsonb_populate_recordset(NULL::public.bom_lines, payload -> 'bom_lines');
  INSERT INTO public.bom_versions (product_code, line_no, version, released_at, released_by, note, line_count, extra, updated_by)
    SELECT product_code, line_no, version, released_at, released_by, note, line_count, extra, updated_by FROM jsonb_populate_recordset(NULL::public.bom_versions, payload -> 'bom_versions');
  INSERT INTO public.combo_sets (product_code, revision, extra, updated_by)
    SELECT product_code, revision, extra, updated_by FROM jsonb_populate_recordset(NULL::public.combo_sets, payload -> 'combo_sets');
  INSERT INTO public.combo_set_lines (product_code, line_no, item_code, qty, standard_scope, price_included, note, extra, updated_by)
    SELECT product_code, line_no, item_code, qty, standard_scope, price_included, note, extra, updated_by FROM jsonb_populate_recordset(NULL::public.combo_set_lines, payload -> 'combo_set_lines');
  INSERT INTO public.combo_set_history (product_code, line_no, at, by_staff_id, note, extra, updated_by)
    SELECT product_code, line_no, at, by_staff_id, note, extra, updated_by FROM jsonb_populate_recordset(NULL::public.combo_set_history, payload -> 'combo_set_history');
  INSERT INTO public.work_orders (id, sales_order_id, item_code, qty, stage, material_issued, order_line, sort_order, extra, updated_by)
    SELECT id, sales_order_id, item_code, qty, stage, material_issued, order_line, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.work_orders, payload -> 'work_orders');
  INSERT INTO public.vendors (id, name, city, supplies, state, gstin, contact, phone, email, payment_terms_days, active, is_msme, udyam_no, sort_order, extra, updated_by)
    SELECT id, name, city, supplies, state, gstin, contact, phone, email, payment_terms_days, active, is_msme, udyam_no, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.vendors, payload -> 'vendors');
  INSERT INTO public.indents (id, indent_date, raised_by, department, source, need_by, reason, status, sort_order, extra, updated_by)
    SELECT id, indent_date, raised_by, department, source, need_by, reason, status, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.indents, payload -> 'indents');
  INSERT INTO public.indent_lines (indent_id, line_no, material_code, qty, approved_qty, ordered_qty, extra, updated_by)
    SELECT indent_id, line_no, material_code, qty, approved_qty, ordered_qty, extra, updated_by FROM jsonb_populate_recordset(NULL::public.indent_lines, payload -> 'indent_lines');
  INSERT INTO public.indent_history (indent_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT indent_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.indent_history, payload -> 'indent_history');
  INSERT INTO public.purchase_orders (id, po_date, vendor_id, indent_id, due_date, status, reason, sort_order, extra, updated_by)
    SELECT id, po_date, vendor_id, indent_id, due_date, status, reason, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.purchase_orders, payload -> 'purchase_orders');
  INSERT INTO public.purchase_order_lines (purchase_order_id, line_no, material_code, qty, rate, received_qty, rejected_qty, order_unit, unit_factor, order_qty, order_rate, extra, updated_by)
    SELECT purchase_order_id, line_no, material_code, qty, rate, received_qty, rejected_qty, order_unit, unit_factor, order_qty, order_rate, extra, updated_by FROM jsonb_populate_recordset(NULL::public.purchase_order_lines, payload -> 'purchase_order_lines');
  INSERT INTO public.purchase_order_history (purchase_order_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT purchase_order_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.purchase_order_history, payload -> 'purchase_order_history');
  INSERT INTO public.gate_passes (id, direction, pass_date, purchase_order_id, party_id, vehicle, party_document, status, grn_id, returnable, purpose, expected_back, reference, sort_order, extra, updated_by)
    SELECT id, direction, pass_date, purchase_order_id, party_id, vehicle, party_document, status, grn_id, returnable, purpose, expected_back, reference, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.gate_passes, payload -> 'gate_passes');
  INSERT INTO public.gate_pass_lines (gate_pass_id, line_no, material_code, qty, returned_qty, rejected_at_gate, rejection_reason, arrived_unit, arrived_unit_qty, rejected_unit_qty, extra, updated_by)
    SELECT gate_pass_id, line_no, material_code, qty, returned_qty, rejected_at_gate, rejection_reason, arrived_unit, arrived_unit_qty, rejected_unit_qty, extra, updated_by FROM jsonb_populate_recordset(NULL::public.gate_pass_lines, payload -> 'gate_pass_lines');
  INSERT INTO public.gate_pass_history (gate_pass_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT gate_pass_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.gate_pass_history, payload -> 'gate_pass_history');
  INSERT INTO public.grns (id, grn_date, gate_entry_id, purchase_order_id, vendor_id, received_by, status, return_pass_id, sort_order, extra, updated_by)
    SELECT id, grn_date, gate_entry_id, purchase_order_id, vendor_id, received_by, status, return_pass_id, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.grns, payload -> 'grns');
  INSERT INTO public.grn_lines (grn_id, line_no, material_code, received_qty, accepted_qty, rejected_qty, rejection_reason, billed_qty, counted_qty, counted_unit, theoretical_qty, weighed_kg, weight_variance_pct, extra, updated_by)
    SELECT grn_id, line_no, material_code, received_qty, accepted_qty, rejected_qty, rejection_reason, billed_qty, counted_qty, counted_unit, theoretical_qty, weighed_kg, weight_variance_pct, extra, updated_by FROM jsonb_populate_recordset(NULL::public.grn_lines, payload -> 'grn_lines');
  INSERT INTO public.grn_history (grn_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT grn_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.grn_history, payload -> 'grn_history');
  INSERT INTO public.vendor_bills (id, vendor_invoice_no, vendor_invoice_date, booked_on, vendor_id, grn_id, purchase_order_id, status, match_status, approved_total, sort_order, extra, updated_by)
    SELECT id, vendor_invoice_no, vendor_invoice_date, booked_on, vendor_id, grn_id, purchase_order_id, status, match_status, approved_total, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.vendor_bills, payload -> 'vendor_bills');
  INSERT INTO public.vendor_bill_lines (vendor_bill_id, line_no, material_code, qty, rate, po_rate, accepted_qty, billed_amount, billed_unit, billed_unit_qty, billed_unit_rate, extra, updated_by)
    SELECT vendor_bill_id, line_no, material_code, qty, rate, po_rate, accepted_qty, billed_amount, billed_unit, billed_unit_qty, billed_unit_rate, extra, updated_by FROM jsonb_populate_recordset(NULL::public.vendor_bill_lines, payload -> 'vendor_bill_lines');
  INSERT INTO public.vendor_bill_payments (vendor_bill_id, line_no, paid_on, amount, mode, reference, extra, updated_by)
    SELECT vendor_bill_id, line_no, paid_on, amount, mode, reference, extra, updated_by FROM jsonb_populate_recordset(NULL::public.vendor_bill_payments, payload -> 'vendor_bill_payments');
  INSERT INTO public.vendor_bill_history (vendor_bill_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT vendor_bill_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.vendor_bill_history, payload -> 'vendor_bill_history');
  INSERT INTO public.debit_notes (id, note_date, vendor_id, vendor_bill_id, reason, taxable, tax, total, sort_order, extra, updated_by)
    SELECT id, note_date, vendor_id, vendor_bill_id, reason, taxable, tax, total, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.debit_notes, payload -> 'debit_notes');
  INSERT INTO public.material_requisitions (id, requested_on, requested_by, work_order_id, purpose, status, previous_status, sort_order, extra, updated_by)
    SELECT id, requested_on, requested_by, work_order_id, purpose, status, previous_status, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.material_requisitions, payload -> 'material_requisitions');
  INSERT INTO public.material_requisition_lines (material_requisition_id, line_no, material_code, qty, approved_qty, issued_qty, received_qty, returned_qty, return_reason, indent_id, extra, updated_by)
    SELECT material_requisition_id, line_no, material_code, qty, approved_qty, issued_qty, received_qty, returned_qty, return_reason, indent_id, extra, updated_by FROM jsonb_populate_recordset(NULL::public.material_requisition_lines, payload -> 'material_requisition_lines');
  INSERT INTO public.material_requisition_history (material_requisition_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT material_requisition_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.material_requisition_history, payload -> 'material_requisition_history');
  INSERT INTO public.stock_ledger (id, posted_at, posted_time, material_code, movement_type, reference, qty_in, qty_out, balance, posted_by, sort_order, extra, updated_by)
    SELECT id, posted_at, posted_time, material_code, movement_type, reference, qty_in, qty_out, balance, posted_by, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.stock_ledger, payload -> 'stock_ledger');
  INSERT INTO public.stock_adjustments (id, adjusted_on, raised_by, material_code, system_qty, counted_qty, reason, status, sort_order, extra, updated_by)
    SELECT id, adjusted_on, raised_by, material_code, system_qty, counted_qty, reason, status, sort_order, extra, updated_by FROM jsonb_populate_recordset(NULL::public.stock_adjustments, payload -> 'stock_adjustments');
  INSERT INTO public.stock_adjustment_history (stock_adjustment_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by)
    SELECT stock_adjustment_id, line_no, at, at_time, by_staff_id, action, note, tone, extra, updated_by FROM jsonb_populate_recordset(NULL::public.stock_adjustment_history, payload -> 'stock_adjustment_history');
END $$;
REVOKE ALL ON FUNCTION public.erp_load_sample(jsonb, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.erp_load_sample(jsonb, boolean) TO authenticated;

-- The JSON record store of phases 2 and 3 is replaced by the tables above.
DROP TABLE IF EXISTS public.erp_records CASCADE;
DROP FUNCTION IF EXISTS public.erp_records_touch() CASCADE;
